### PR TITLE
WIP: add concurrency tests and database locks

### PR DESCRIPTION
**Pull request by tiltec**
Related to #409 
currently has unhandled deadlocks, needs more work or another approach

### CODE REVIEW

**Comment by tiltec** [comment]
@nicksellen 
What's your opinion on this PR?

**Comment by nicksellen** [comment]
Maybe we should close this one now? It's around 2.5 years old... I think the underlying issue is actually still very interesting and probably relevant for a lot of web apps, but also quite difficult to address ourselves with the current level of framework support (or lack of it).

**Comment by tiltec** [comment]
I'll have another look at it soon, I actually have it in mind from time to time when one of the weirder backend errors come up in Sentry.

I might apply some locking similar as in this PR, but not add the test. It also might need some frontend changes, otherwise it might be confused and show a failed request, whereas the user just clicked the button twice very fast. Actually, most of the backend errors should go away when buttons are properly debounced…

In any case, I'll close this one soon!

**Comment by nicksellen** [comment]
Yup, seems fine to be open if it's still active in your mind :)

**Pull request closed without merging**
