### PR TITLE
WIP: Weekly summary emails date fix

### PR DESCRIPTION
**Pull request by lwm**
@nicksellen, I've tried to add a test for https://github.com/yunity/karrot-frontend/issues/1083 that proves the thing is doing something wrong and am instead getting, what appears to me, the correct result (test is passing). If you could take a look at this, it'd be great.

My test sets up your example in https://github.com/yunity/karrot-frontend/issues/1083#issue-351889961 whereby the summary email is sent on Sunday the 19th (like the crontab specifies) and should give us the summary for 12th -> 18th. Am I reading that right?

Time remains confusing.

Something for https://github.com/yunity/karrot-frontend/issues/1083.
Refs: https://github.com/yunity/karrot-backend/pull/588

### CODE REVIEW

**Comment by nicksellen** [comment]
Ah, interesting. It definitely still sends Saturday -> Saturday emails as I get them each week. I'll have a peek.

Thanks for looking into it :)

**Comment by lwm** [comment]
> Thanks for looking into it :)

Sure thing! I'll try to cause the bug when I look at this tomorrow.

**Comment by nicksellen** [comment]
Aha, I found the cause, it's because of how it's rendered in the template:

https://github.com/yunity/karrot-backend/blob/c20446e2c549d1797ade28f05196ed123ae2c86a/foodsaving/groups/templates/group_summary.mjml#L12

Which uses the jinja2 date filter, which is defined as:

https://github.com/yunity/karrot-backend/blob/c20446e2c549d1797ade28f05196ed123ae2c86a/foodsaving/utils/email_utils.py#L19-L24

Which uses `get_current_timezone()` but there is no timezone override specified.

It could be added inside the task:

https://github.com/yunity/karrot-backend/blob/c20446e2c549d1797ade28f05196ed123ae2c86a/foodsaving/groups/tasks.py#L104

... or further down in the rendering.

**Comment by nicksellen** [comment]
Do you want to implement the fix @lwm? Or I could.

**Comment by lwm** [comment]
Aha! OK, I want to get back on this. I'll make time tomorrow, thanks for taking a look!

**Comment by lwm** [comment]
Ack, I'm booked out this month and I don't think I'll get around to it any time soon :bomb:

**Pull request closed without merging**
