### PR TITLE
Update emails.py

### PR DESCRIPTION
**Pull request by Ahrkano**
in calculate_group_summary_dates():
relativedelta(days=7) -> relativedelta(days=6)

### CODE REVIEW

**Comment by tiltec** [comment]
Hi @Ahrkano, welcome to Karrot! Is this a bug fix?

**Comment by nicksellen** [comment]
I assume it's for the summary emails "Sunday to Sunday" issue? (Or is it Saturday to Saturday).

Although this would result in one day not being included in the reporting period.

**Comment by nicksellen** [comment]
https://github.com/yunity/karrot-frontend/issues/1083 is the issue I was talking about (was just replying on my phone before).

It needs to still include the data from the whole week:

```
saturday | sunday | ... | saturday | sunday
               |<-------------------------->|
```

So it's from Saturday midnight to Saturday midnight. When printing the day name it ends up with Saturday for each end, but it's not including things that happened throughout the first saturday.

Hopefully that makes the issue clearer @Ahrkano :)

**Comment by lwm** [comment]
@Ahrkano, please see https://github.com/yunity/karrot-frontend/issues/1083#issuecomment-451774685. If you're picking this up again, please do let me know and I'll work on something else :+1:

**Comment by tiltec** [comment]
The issue was fixed by https://github.com/yunity/karrot-backend/pull/658

**Pull request closed without merging**
