### PR TITLE
Add user photo field using versatileimagefield

### PR DESCRIPTION
**Pull request by nicksellen**
The upload worked but I couldn't actually see how to serve the files, the provided URLs did not work directly.

### CODE REVIEW

**Comment by tiltec** [comment]
Does it dump them into `uploads/user__photos/`?

**Comment by nicksellen** [comment]
Yes, maybe need to create the dir first (I tried it with the `uploads/` prefix and it created `__sized__` and `user__photos` dirs at the top level).

The urls it returned were like `/api/auth/user/__sized__/blahblhahblahbla/oijsef/bouasef.jpg` which our `urls.py` doesn't seem to have any clue about. The docs didn't seem to help me out either.

**Comment by nicksellen** [comment]
You can use curl to upload them, something like:

```
curl -XPATCH localhost:8000/api/auth/user/ -F photo=@someimage.jpg
``

**Comment by tiltec** [comment]
VersatileImageField extends Django's `ImageField`, I found the documentation here: https://docs.djangoproject.com/en/2.0/topics/files/

I'll work on this PR.

**Comment by tiltec** [comment]
@nicksellen 
You wanna have a look at it before I merge?

**Comment by tiltec** [comment]
The default storage backend is [FileSystemStorage](https://docs.djangoproject.com/en/2.0/ref/files/storage/#the-filesystemstorage-class), which dumps the files in the `MEDIA_ROOT` folder.

**Comment by tiltec** [comment]
Could use some tests too...

**Comment by tiltec** [comment]
There are security considerations when serving user-uploaded content from your own domain: https://docs.djangoproject.com/en/2.0/topics/security/#user-uploaded-content-security

We could serve the images from a separate domain (e.g. usercontent.foodsaving.world) or use some CDN.

**Pull request merged**
