### PR TITLE
Add backend support for group photos

### PR DESCRIPTION
**Pull request by cstefanj**
@tiltec I added the migration file now, as well as the example photo.jpg that the test uses (same that was in the userauth folder). There was a FileNotFound test error before.

### CODE REVIEW

**Comment by tiltec** [comment]
Looks good! I will add a frontend implementation in the next days and then merge this PR.

**Comment by cstefanj** [comment]
@tiltec I added the migration file now, as well as the example photo.jpg that the test uses (same that was in the userauth folder). There was a FileNotFound test error before.

**Comment by tiltec** [comment]
@nicksellen had the great idea to add the group photo to the email notifications, replacing the Karrot logo. That could be a good follow-up PR :)

**Comment by cstefanj** [comment]
Hi! I made those changes now. Sorry about the double commits, was a bit fast on the trigger the first time around.

Would be happy to work on the other photo feature as well if there's anything I can do. Back to full-time work this week though so I'm afraid my time bandwidth will drop a bit from now on .... :-|

**Comment by tiltec** [comment]
It's merged :) Will be online at dev.karrot.world in a few minutes. I'm happy to support you when you find time to work on Karrot again...

**Comment by lwm** [comment]
:rocket:

**Comment by cstefanj** [comment]
@tiltec Great! :-) A huge milestone for me, my first open source contribution! And first time working on something larger together with others, have only done my own projects until now. Thanks a million for all the help and guidance, I learned a lot! Would love to continue, I also think Karrot is a very worthwhile cause. But as mentioned, just have to find the time .... :-)

**Pull request merged**
