### PR TITLE
rename pickups to activities in notification mail subject

### PR DESCRIPTION
**Pull request by dwaxweiler**
I have fixed the notification e-mail subject. See https://github.com/yunity/karrot-frontend/issues/2425.

Do I need to update all occurrences in the *.po localization files as well or will a script take care of this after the pull request is merged?

### CODE REVIEW

**Comment by tiltec** [comment]
Great! You should run `manage.py makemigrations` to update the English po file, or you could also edit it manually (if you don't have the dev environment set up yet).

**Comment by dwaxweiler** [comment]
@tiltec I have done so now.

**Comment by tiltec** [comment]
Alright, next challenge :( - seems this messag is already translated elsewhere, so running `makemessages` collapses them into one. Have a look at the end of https://app.circleci.com/pipelines/github/yunity/karrot-backend/1631/workflows/202d67f4-e59f-469f-a6ce-dde8e4cf2de9/jobs/6858/parallel-runs/0/steps/0-108 to see the diff.

You could either modify the English po file to match the diff, or run `makemessages`.

**Comment by dwaxweiler** [comment]
@tiltec Done! :)

**Review by tiltec — APPROVED** [review]

**Pull request merged**
